//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmallInfo.Data
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;

    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.Addresses = new ObservableCollection<Address>();
            this.OtherAccountInfoes = new ObservableCollection<OtherAccountInfo>();
            this.Phones = new ObservableCollection<Phone>();
            this.Payments = new ObservableCollection<Payment>();
            this.Pledges = new ObservableCollection<Pledge>();
            PledgesW_Balance = new ObservableCollection<Pledge>();
        }

        public int AccountId { get; set; }
        public string NameTitle { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string HNameTitle { get; set; }
        public string HFirstName { get; set; }
        public string HLastName { get; set; }
        public string FathersName { get; set; }
        public string ShvarsName { get; set; }
        public string Note { get; set; }
        public string HNameEnd { get; set; }

        public Address defaultAddress;
        public decimal Running { get; set; }
        public ObservableCollection<Pledge> PledgesW_Balance { get; set; }
        public decimal Balance { get; set; }

        public string EComboBoxString { get { SetDefaultAddress(); return LastName + " " + FirstName + " " + defaultAddress; } }
        public string HComboBoxString { get { return HLastName + " " + HFirstName + " " + "בן" + " " + FathersName; } }

        void SetDefaultAddress()
        {
            foreach (Address address in Addresses)
            {
                if (address.Default == true)
                    defaultAddress = address;
            }
        }

        void SetPayments()
        {
            PledgesW_Balance.Clear();

            foreach (Pledge pledge in Pledges)
            {
                pledge.Payments = new List<Apply>();

                foreach (Payment payment in Payments)
                {
                    foreach (Apply apply in payment.Applies)
                    {
                        if (apply.PledgeId == pledge.PledgeId)
                        {
                            pledge.Payments.Add(apply);
                            apply.pledge = pledge;
                        }
                    }
                }
                if (pledge.Balance > 0)
                    PledgesW_Balance.Add(pledge);
            }
        }

        void SetRunning()
        {
            Running = 0;
            foreach (Pledge pledge in Pledges)
            {
                Running += pledge.Balance;
                pledge.Running = Running;
            }
        }

        void SetBalance()
        {
            Balance = 0;
            foreach (Pledge pledge in Pledges)
                Balance += pledge.Amount;
            foreach (Payment payment in Payments)
                Balance -= payment.Amount;
        }

        public void SetAccountsRecords()
        {
            SetPayments();
            SetRunning();
            SetBalance();
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Address> Addresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OtherAccountInfo> OtherAccountInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Phone> Phones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Payment> Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Pledge> Pledges { get; set; }
    }
}