//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmallInfo.Data
{
    using System;
    using System.Collections.Generic;

    public partial class Apply
    {
        public int ApplyId { get; set; }
        public decimal ApplyAmount { get; set; }
        public int PledgeId { get; set; }
        public int PaymentId { get; set; }

        public virtual Payment Payment { get; set; }

        public Pledge pledge { get; set; }
    }
}
