//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmallInfo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campaign
    {
        public int CampaignId { get; set; }
        public string Campaign1 { get; set; }
        public Nullable<bool> IsDefault { get; set; }
    }
}
